---
schema: public  # Schema name e.g. public. One mapper file per schema and you can have multiple tables in the same mapper file as long as schema is same, otherwise create multiple mapper files e.g. mapper1.xml, mapper2.xml or <table_name>.xml etc. under mappers folder of your config dir.
tables:
  - table: emp   # update this for your source table name
    mapper:
      id: Test
      processorID: Test
      publishBefore: false # publishBefore - Global setting, that specifies if before values have to be published for all columns. This setting could be overridden at each column level
      passThrough: true # set it to true if you don't need to map individual columns. You always need to have the key column mappings.
      columns:
        - src: empno
          target: EmpNum
          type: INT
          publishBefore: false
        # - src: fname
        #   target: FName
        # - src: lname
        #   target: LName
        # - src: job
        #   target: Job
        # - src: mgr
        #   target: Manager
        #   type: INT
        # - src: hiredate
        #   target: HireDate
        #   # type: DATE_TIME
        # - src: sal
        #   target: Salary
        #   type: DOUBLE
        # - src: comm
        #   target: Commission
        #   type: DOUBLE
        # - src: dept
        #   target: Department
        #   type: INT
