connectionId: jobConfigConnection
jobTypeId: jobType1
jobStream: loaderJobStream
jobConfigSet: loaderJobConfigs
completedJobsSet: loaderCompletedJobs
initialDelay: 10000
numManagementThreads: 2
metricsReporter:
  - REDIS_TS_METRICS_REPORTER
heartBeatConfig:
  key: hb-jobManager
  expiry: 30000
jobHeartBeatKeyPrefix: "hb-job:"
jobHeartbeatCheckInterval: 45000
jobClaimerConfig:
  initialDelay: 10000
  claimInterval: 60000
  heartBeatConfig:
    key: "hb-job:"
    expiry: 30000
  maxNumberOfJobs: 2
  consumerGroup: loaderJobGroup
  batchSize: 1
