connectionId: jobConfigConnection
job:
  jobConfig:
    - name: initial_load
      config: TaskCreator.yml
      variables:
        connectionProvider: GemfireConnectionProvider
        connectionId: gemfireConnection
