apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-connect-oracle # deployment name
  labels:
    app: redis-connect-oracle # deployment label
spec:
  replicas: 2 # replicas for HA
  selector:
    matchLabels:
      app: redis-connect-oracle # which pods is the deployment managing, as defined by the pod template
  template: # pod template
    metadata:
      labels:
        app: redis-connect-oracle 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-connect-oracle # must match Deployment:metadata:labels:app
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - name:  redis-connect-oracle # Container name 
        image: redislabs/redis-connect-oracle:pre-release-alpine #repo/image:tag
#### uncomment the following two lines while you are setting up your 
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
####
        command: ["/opt/redislabs/redis-connect-oracle/bin/redisconnect.sh", "start"] 
        imagePullPolicy: Always # IfNotPresent # Always pull image
        resources:
          limits:
            cpu: "4000m"
            memory: "1024Mi"
          requests:
            cpu: "4000m"
            memory: "256Mi"
        ports:  
        - containerPort: 8282 # exposed container port to the REST API 
          protocol: TCP
        env:
          - name: REDISCONNECT_LOGBACK_CONFIG
            value: "/opt/redislabs/redis-connect-oracle/config/logback.xml"
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_LOGBACK_CONFIG
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_CONFIG
            value: "/opt/redislabs/redis-connect-oracle/config/fromconfigmap"
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_CONFIG
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_REST_API_ENABLED
            value: "false"
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_REST_API_ENABLED
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_REST_API_PORT
            value: "8282"
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_REST_API_PORT
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_SOURCE_USERNAME
            value: redisconnectuser
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_SOURCE_USERNAME
            #     name: redis-connect-oracle-config
            # valueFrom:
            #   secretKeyRef:
            #     key: username
            #     name: redis-connect-secret
          - name: REDISCONNECT_SOURCE_PASSWORD
            value: redisconnectpassword
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_SOURCE_PASSWORD
            #     name: redis-connect-oracle-config
            # valueFrom:
            #   secretKeyRef:
            #     key: password
            #     name: redis-connect-secret
          - name: REDISCONNECT_JAVA_OPTIONS
            value: "-XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx1g"
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_JAVA_OPTIONS
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_TARGET_PASSWORD
            value: test
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_TARGET_PASSWORD
            #     name: redis-connect-oracle-config
          - name: REDISCONNECT_TARGET_USERNAME
            value: test
            # valueFrom:
            #   configMapKeyRef:
            #     key: REDISCONNECT_TARGET_USERNAME
            #     name: redis-connect-oracle-config            
        volumeMounts:
        # - name: redis-connect-oracle-pv
        #   mountPath: "/opt/redislabs/redis-connect-oracle"
        - name: tmpfsdir # Pod volumes to mount into the container's filesystem. Cannot be updated.
          mountPath: /tmpfs
        - name: config-volume
          mountPath: /opt/redislabs/redis-connect-oracle/config/fromconfigmap  # must match env:REDISCONNECT_CONFIG
        - name: custom-stage-volume
          mountPath: /opt/redislabs/redis-connect-oracle/extlib  # Redis Connect expects the custom stage jars here
      volumes:
      - name: config-volume
        configMap:
          name: redis-connect-oracle-config
          items:
          - key: JobConfig.yml
            path: JobConfig.yml
          - key: JobManager.yml
            path: JobManager.yml
          - key: Setup.yml
            path: Setup.yml
          - key: env.yml
            path: env.yml
          - key: mapper1.yml
            path: mappers/mapper1.yml
      - name: custom-stage-volume  
        configMap:
          name: redis-connect-oracle-config
          items:  # define as many custom stages as you have here
          - key: redis-connect-custom-stage-demo-1.0-SNAPSHOT.jar
            path: redis-connect-custom-stage-demo-1.0-SNAPSHOT.jar
      - name: tmpfsdir
        emptyDir:  # node-ephemeral volume
          medium: Memory
      # - name: redis-connect-oracle-pv
      #   persistentVolumeClaim:
      #     claimName: redis-connect-oracle-pvc                 
---
# RedisConnect service with name 'redis-connect-service'
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-connect-api-service       # name should not be 'redis-connect' 
# spec:
#   type: ClusterIP
#   ports:
#     - port: 80
#       targetPort: 8282
#   selector:
#     app: redis-connect-api-service
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-connect-oracle-pvc 
# spec:
#   storageClassName: gp2
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---