jobId: ${jobId}
producerConfig:
  producerId: RDB_INITIAL_LOAD_PRODUCER
  connectionId: RDBConnection
  batchSize: 500
  startRecord: ${startRecord}
  endRecord: ${endRecord}
  loadQuery: ${loadQuery}
  table: ${table}
pipelineConfig:
  eventTranslator: "RDB_RS_TO_OP_TRANSLATOR"
  checkpointConfig:
    providerId: REDIS_HASH_CHECKPOINT_READER
    connectionId: targetConnection
    checkpoint: "${jobId}"
  stages:
    HashWriteStage:
      handlerId: REDIS_HASH_WRITER
      connectionId: targetConnection
      metricsEnabled: false
      prependTableNameToKeys: true
      deleteOnKeyUpdate: true
      async: true
    CheckpointStage:
      handlerId: REDIS_HASH_CHECKPOINT_WRITER
      connectionId: targetConnection
      metricEnabled: false
      async: true
      checkpoint: "${jobId}"


