jobId: ${jobId}
jobType: TASK_CREATOR
producerConfig:
  producerId: RDB_TASK_CREATOR # internal id
  connectionId: RDBConnection # source connectionId same as env.yml
  jobs:
    - table: RedisConnect.emp # schema.table
      numJobs: 5
      config: JobConfig.yml
      loadQuery: "SELECT * FROM (SELECT e.*, ROW_NUMBER() OVER (ORDER BY e.empno) RowIndex FROM RedisConnect.emp e) emps WHERE emps.RowIndex BETWEEN ${start} and ${end}"
