jobId: ${jobId}
producerConfig:
  producerId: LOG_MINER_EVENT_PRODUCER
  connectionId: RDBConnection
  metaConnectionId: RDBMetadataConnection
  tables:
    - HR.EMPLOYEES #schema.table
    - HR.JOBS
  metricsEnabled: false
pipelineConfig:
  eventTranslator: "ORACLE_LOG_MINER_TRANSLATOR"
  checkpointConfig:
    providerId: REDIS_HASH_CHECKPOINT_READER
    connectionId: targetConnection
    checkpoint: "${jobId}-${schema}"
  stages:
    HashWriteStage:
      handlerId: REDIS_HASH_WRITER
      connectionId: targetConnection
      metricsEnabled: false
      prependTableNameToKeys: true
      deleteOnKeyUpdate: true
      async: true
    CheckpointStage:
      handlerId: REDIS_HASH_CHECKPOINT_WRITER
      connectionId: targetConnection
      metricEnabled: false
      async: true
      checkpoint: "${jobId}-${schema}"