connectionId: jobConfigConnection
job:
  metrics:
    connectionId: metricsConnection
    retentionInHours: 12
    keys:
      - key: "HR:EMPLOYEES:C:Throughput"
        retentionInHours: 4
        labels:
          schema: HR
          table: EMPLOYEES
          op: C
      - key: "HR:EMPLOYEES:U:Throughput"
        retentionInHours: 4
        labels:
          schema: HR
          table: EMPLOYEES
          op: U
      - key: "HR:EMPLOYEES:D:Throughput"
        retentionInHours: 4
        labels:
          schema: HR
          table: EMPLOYEES
          op: D
      - key: "HR:EMPLOYEES:Latency"
        retentionInHours: 4
        labels:
          schema: HR
          table: EMPLOYEES
  jobConfig:
    - name: ORACLE-HR
      config: JobConfig.yml
      variables:
        schema: HR