connectionId: jobConfigConnection
job:
  metrics:
    connectionId: metricsConnection
    retentionInHours: 12
    keys:
      - key: "RedisConnect:emp:C:Throughput"
        retentionInHours: 4
        labels:
          schema: RedisConnect
          table: emp
          op: C
      - key: "RedisConnect:emp:U:Throughput"
        retentionInHours: 4
        labels:
          schema: RedisConnect
          table: emp
          op: U
      - key: "RedisConnect:emp:D:Throughput"
        retentionInHours: 4
        labels:
          schema: RedisConnect
          table: emp
          op: D
      - key: "RedisConnect:emp:Latency"
        retentionInHours: 4
        labels:
          schema: RedisConnect
          table: emp
  jobConfig:
    - name: RedisConnect-mysql
      config: JobConfig.yml
      variables:
        database: RedisConnect
        sourceValueTranslator: SOURCE_RECORD_TO_OP_TRANSLATOR

