jobId: ${jobId}
producerConfig:
  producerId: RDB_EVENT_PRODUCER
  connectionId: sourceRDBConnection
  tables:
    - public.emp  # SCHEMA.TABLE must change this for your DB.schema.table
  pollingInterval: 5
  # metricsKey: testdb-emp
  # metricsEnabled: false
pipelineConfig:
  bufferSize: 1024
  eventTranslator: "${sourceValueTranslator}"
  checkpointConfig:
    providerId: RDB_CHECKPOINT_READER
    connectionId: targetConnection
    checkpoint: "${jobId}-${database}"
    rdbType: "postgres"
  stages:
    # CustomStage:  # implements the custom stage in `redis-connect-custom-stage-demo.jar`
    #   handlerId: TO_UPPER_CASE
    HashWriteStage:
      handlerId: REDIS_HASH_WRITER
      connectionId: targetConnection
      metricsEnabled: false
      prependTableNameToKeys: true
      deleteOnKeyUpdate: true
      async: true
    # StringWriteStage:
    #   handlerId: REDIS_OP_TO_STRING_WRITER
    #   connectionId: targetConnection
    #   metricsEnabled: false
    #   prependTableNameToKeys: false
    #   deleteOnKeyUpdate: true
    #   async: true
    CheckpointStage:
      handlerId: REDIS_OP_CP_WRITER
      connectionId: targetConnection
      metricEnabled: false
      async: true
      checkpoint: "${jobId}-${database}"


