schema: HR
tables:
  - table: EMPLOYEES
    mapper:
      id: employees
      processorID: employees
      publishBefore: false
      passThrough: true
      columns:
        - src: EMPLOYEE_ID
          target: EMPLOYEE_ID
          type: INT
          publishBefore: false
        - src: HIRE_DATE
          target: HIRE_DATE
          type: DATE_TIME
  - table: JOBS
    mapper:
      id: Jobs
      processorID: Jobs
      publishBefore: false
      passThrough: true
      columns:
        - src: JOB_ID
          target: JobId
          type: INT
