jobId: ${jobId}
producerConfig:
  producerId: RDB_EVENT_PRODUCER
  connectionId: RDBConnection
  tables:
    - public.emp #schema.table
    #- public.heartbeat # heartbeat table to keep postgres active
  metricsKey: RedisConnect-emp
  metricsEnabled: false
pipelineConfig:
  eventTranslator: "${sourceValueTranslator}"
  checkpointConfig:
    providerId: RDB_SQL_CHECKPOINT_READER
    connectionId: targetConnection
    checkpoint: "${jobId}-${database}"
    rdbType: "postgres"
  stages:
    HashWriteStage:
      handlerId: REDIS_HASH_WRITER
      connectionId: targetConnection
      metricsEnabled: false
      prependTableNameToKeys: true
      deleteOnKeyUpdate: true
      async: true
    CheckpointStage:
      handlerId: REDIS_HASH_CHECKPOINT_WRITER
      connectionId: targetConnection
      metricEnabled: false
      async: true
      checkpoint: "${jobId}-${database}"
