connectionId: jobConfigConnection
job:
  metrics:
    connectionId: metricsConnection
    retentionInHours: 12
    keys:
      - key: "public:emp:C:Throughput"
        retentionInHours: 4
        labels:
          schema: public
          table: emp
          op: I
      - key: "public:emp:U:Throughput"
        retentionInHours: 4
        labels:
          schema: public
          table: emp
          op: U
      - key: "public:emp:D:Throughput"
        retentionInHours: 4
        labels:
          schema: public
          table: emp
          op: D
      - key: "public:emp:Latency"
        retentionInHours: 4
        labels:
          schema: public
          table: emp
  jobConfig:
    - name: RedisConnect-postgres
      config: JobConfig.yml
      variables:
        database: RedisConnect
        sourceValueTranslator: SOURCE_RECORD_TO_OP_TRANSLATOR
