jobId: ${jobId}
jobType: TASK_CREATOR
producerConfig:
  producerId: RDB_TASK_CREATOR # internal id
  connectionId: RDBConnection # source connectionId same as env.yml
  jobs:
    - table: HR.EMPLOYEES # schema.table
      numJobs: 5
      config: JobConfig.yml
      loadQuery: "SELECT * FROM (SELECT e.*, ROW_NUMBER() OVER (ORDER BY EMPLOYEE_ID) RowIndex FROM HR.EMPLOYEES e) WHERE RowIndex BETWEEN ${start} and ${end}"
